### ISSUE TITLE
Compile from scratch

### ISSUE THREAD

**Issue by holgeroettel** [Duckbox-Developers/max-tdt#1]
Dear guys,

hopefully i dont annoy you out there.
I started with ubuntu 12.04 64Bit, fresh Server install from a Box. Installed built-essentials, git cloned, started with the setuptdt.sh.
I want to cross-compile for sh4 (UFS910, 912, 913), to get tun.ko (final goal)

First run, there was a bug in binutils. In the file bfd/doc/bfd.texfile there where missing @@ instead of @. So i added to Patch, since that was overriden by new run, i Patchen the SPEC, to copy my file in.

Second i run into a "segmentation fault", this shouldn't happen, never the less i switched to gcc 4.7.3 instead of 4.6.3

Third i ran into a texfile version thing. Something with itemlist, missing itemx. My 5.3 was certainly too new, so i downgraded to 4,9 and it vanished.

Forth i am stuck with mpc.

/bin/grep: /opt/max-tdt/tdt/tufsbox/cdkroot/opt/max-tdt/tdt/tufsbox/cdkroot/usr/lib/libgmp.la: No such file or directory
sed: can't read /opt/max-tdt/tdt/tufsbox/cdkroot/opt/max-tdt/tdt/tufsbox/cdkroot/usr/lib/libgmp.la: No such file or directory
Duckbox-libtool: link: `/opt/max-tdt/tdt/tufsbox/cdkroot/opt/max-tdt/tdt/tufsbox/cdkroot/usr/lib/libgmp.la' is not a valid libtool archive

After some lmgtfy my best shot seems to be GMP-MPFR-MPC. Reading Makefile.in they would be compiled in the right follow, but something seems to get to libtool. Since we are in a cdkroot, does libtool think it compiled to /usr/lib instead of /opt/max-tdt/tdt/tufsbox/cdkroot/usr/lib?
Or is it more simple an the double quote the problem? Any idea where that may happen? What am i looking for? Makefile.in, somewhat in mpc?

Thanks in advance, hope you get me back on track, get somewhat beaten of it.
Holger Oettel

**Comment by BPanther** [comment]
Hi Holger.

Binutils and "duckbox-libtool" must be ok. Maybe a 64 bit problem - but this is untested, because i use only a 32 bit ubuntu 12.04.5 LTS.
The texinfo problem is on some systems with a too new texinfo. Just build once the texinfo with make texinfo before you build neutrino.
I have tested all buildin gcc versions and all should be buildable without any problems. But neutrino maybe on some functions instable, so that the 4.6 is still the better one.

If you want to use a 64 bit system and/or a newer linux distribution, you should better use the other build system -> https://github.com/Duckbox-Developers/StartHere

Regards, BPanther (Mike)
